### ISSUE TITLE
model file cannot be download

### ISSUE THREAD

**Issue by ForrestPi** [cvlab-tohoku/DSEBImageInpainting#3]
Hello,
http://vision.is.tohoku.ac.jp/~altinel/uploadFiles/celebA.tar.gz cannot be download. Could you provide another one?
Thanks

**Comment by fazilaltinel** [comment]
Hello,

The file is somehow deleted from the server. We are sorry about that. Please find the file in the link below:

https://drive.google.com/open?id=1ulpms4ni4ydJJ2NDm9YIl8zSliulFo7t

Fazil
